keys:
  - &pubkey ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPl1FnQ8PwE7rNoXTYS9O0NZGHGOJIf0/N9W6Y9GTXL7 nalhan.park@gmail.com

creation_rules:
  - path_regex: secrets/[^/]+|.yaml$
    key_groups:
      - age:
        - *pubkey
